import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icons';
import { ConfirmDialog, EmptyState, ErrorState, PageHeader, Progress, Spinner, StatusBadge } from '../components/UI';
import { api } from '../lib/api';
import { formatCurrency, formatDate, toTitle } from '../lib/format';
import { useSubscription } from '../lib/useSubscription';
import { useToast } from '../lib/ToastContext';
import type { Invoice } from '../types/billing';

export default function Billing() {
  const { subscription, loading, error, refresh } = useSubscription();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [invoiceLoading, setInvoiceLoading] = useState(true);
  const [invoiceError, setInvoiceError] = useState('');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const { toast } = useToast();
  const fetchInvoices = useCallback(async () => { setInvoiceLoading(true); setInvoiceError(''); try { setInvoices(await api.getInvoices()); } catch (err) { setInvoiceError(err instanceof Error ? err.message : 'Unable to load invoices.'); } finally { setInvoiceLoading(false); } }, []);
  useEffect(() => { void fetchInvoices(); }, [fetchInvoices]);

  const cancel = async () => { setActionLoading(true); try { const result = await api.cancelSubscription(); toast(result.message); setDialogOpen(false); await refresh(); } catch (err) { toast(err instanceof Error ? err.message : 'Unable to cancel subscription.', 'error'); } finally { setActionLoading(false); } };
  const resume = async () => { setActionLoading(true); try { const result = await api.resumeSubscription(); toast(result.message); await refresh(); } catch (err) { toast(err instanceof Error ? err.message : 'Unable to resume subscription.', 'error'); } finally { setActionLoading(false); } };
  const manage = async () => { setActionLoading(true); try { const { url } = await api.createPortal(); if (url.includes('portal=demo')) toast('Billing portal is simulated in preview mode.', 'info'); else window.location.assign(url); } catch (err) { toast(err instanceof Error ? err.message : 'Stripe is temporarily unavailable.', 'error'); } finally { setActionLoading(false); } };
  const bookingPercent = subscription?.usage.bookingsLimit ? subscription.usage.bookings / subscription.usage.bookingsLimit * 100 : 20;

  return <>
    <PageHeader title="Billing & subscription" description="Manage your plan, payment details, and billing history." actions={<button onClick={manage} disabled={actionLoading || loading} className="btn-secondary"><Icon name="card" size={17}/><span className="hidden sm:inline">Manage billing</span>{actionLoading && <Spinner dark/>}</button>}/>
    {error && <ErrorState message={error} onRetry={refresh}/>} 
    {loading ? <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="card h-72 p-6"><div className="skeleton h-5 w-36 rounded"/><div className="skeleton mt-6 h-24 rounded-xl"/><div className="skeleton mt-5 h-12 rounded-xl"/></div><div className="card h-72 p-6"><div className="skeleton h-5 w-28 rounded"/><div className="skeleton mt-6 h-36 rounded-xl"/></div></div> : subscription && <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]">
      <section className="card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Current subscription</p><div className="mt-2 flex items-center gap-3"><h2 className="text-2xl font-bold text-ink-900">{toTitle(subscription.plan)}</h2><StatusBadge status={subscription.status}/></div><p className="mt-1 text-sm text-slate-500">${subscription.plan === 'STARTER' ? '9' : subscription.plan === 'BUSINESS' ? '79' : '29'} / {subscription.billingInterval || 'month'} · Renews automatically</p></div><Link to="/pricing" className="btn-primary"><Icon name="arrowUp" size={16}/>Change plan</Link></div></div>
        {subscription.status === 'past_due' && <div className="m-5 flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><Icon name="warning" size={19}/><div><p className="text-sm font-semibold">Payment failed</p><p className="mt-0.5 text-xs">Please update your payment method to keep your account active.</p></div></div>}
        {subscription.cancelAtPeriodEnd && <div className="m-5 flex items-start justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3 text-amber-900"><Icon name="clock" size={19}/><div><p className="text-sm font-semibold">Cancellation scheduled</p><p className="mt-0.5 text-xs leading-5">Access continues until {formatDate(subscription.currentPeriodEnd)}.</p></div></div><button className="text-sm font-semibold text-amber-900 underline underline-offset-4" onClick={resume} disabled={actionLoading}>Resume</button></div>}
        <div className="grid gap-x-8 gap-y-5 p-5 sm:grid-cols-2 sm:p-6"><Info label="Billing cycle" value={subscription.billingInterval === 'year' ? 'Yearly' : 'Monthly'} icon="calendar"/><Info label="Next billing date" value={subscription.cancelAtPeriodEnd ? 'Not renewing' : formatDate(subscription.currentPeriodEnd)} icon="clock"/><Info label="Subscription started" value={formatDate(subscription.subscriptionStart)} icon="bookings"/><Info label="Payment status" value={toTitle(subscription.paymentStatus)} icon="card"/></div>
        <div className="flex flex-wrap items-center gap-3 border-t border-slate-100 px-5 py-4 sm:px-6">{subscription.cancelAtPeriodEnd ? <button className="btn-primary" onClick={resume} disabled={actionLoading}>{actionLoading && <Spinner/>}Resume subscription</button> : <button className="text-sm font-semibold text-red-600 hover:text-red-700" onClick={() => setDialogOpen(true)}>Cancel subscription</button>}<span className="text-xs text-slate-400">Changes are synchronized securely through Stripe.</span></div>
      </section>
      <section className="card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-ink-900">Plan usage</p><p className="mt-1 text-xs text-slate-500">Resets {formatDate(subscription.currentPeriodEnd, {month:'short', day:'numeric'})}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon name="trend" size={19}/></span></div><div className="mt-7"><div className="mb-2 flex items-end justify-between"><span className="text-sm text-slate-600">Bookings</span><span className="text-sm font-semibold text-ink-900">{subscription.usage.bookings.toLocaleString()} <span className="font-normal text-slate-400">/ {subscription.usage.bookingsLimit?.toLocaleString() || 'Unlimited'}</span></span></div><Progress value={bookingPercent}/></div><div className="mt-6"><div className="mb-2 flex items-end justify-between"><span className="text-sm text-slate-600">Team members</span><span className="text-sm font-semibold text-ink-900">{subscription.usage.teamMembers} <span className="font-normal text-slate-400">/ {subscription.usage.teamLimit || 'Unlimited'}</span></span></div><Progress value={subscription.usage.teamLimit ? subscription.usage.teamMembers / subscription.usage.teamLimit * 100 : 20}/></div><p className="mt-6 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Need more capacity? Upgrade before reaching your limit to avoid interruptions.</p></section>
    </div>}

    <section className="card mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div><h2 className="font-semibold text-ink-900">Billing history</h2><p className="mt-0.5 text-xs text-slate-500">View and download your previous invoices.</p></div></div>
      {invoiceError ? <div className="p-5"><ErrorState message={invoiceError} onRetry={fetchInvoices}/></div> : invoiceLoading ? <InvoiceSkeleton/> : invoices.length === 0 ? <EmptyState title="No invoices yet" description="Your invoices will appear here after your first successful payment."/> : <>
        <div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-xs font-semibold uppercase tracking-wider text-slate-400"><th className="px-6 py-3">Invoice</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Plan</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{invoices.map((invoice) => <tr key={invoice.id} className="text-sm hover:bg-slate-50/60"><td className="px-6 py-4 font-semibold text-ink-900">{invoice.number}</td><td className="px-4 py-4 text-slate-600">{formatDate(invoice.date)}</td><td className="px-4 py-4 font-medium text-ink-800">{formatCurrency(invoice.amount, invoice.currency)}</td><td className="px-4 py-4"><StatusBadge status={invoice.status}/></td><td className="px-4 py-4 text-slate-600">{toTitle(invoice.plan)}</td><td className="px-6 py-4"><div className="flex justify-end gap-1">{invoice.hostedInvoiceUrl && <a href={invoice.hostedInvoiceUrl} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 hover:text-ink-900" aria-label={`View ${invoice.number}`}><Icon name="external" size={16}/></a>}{invoice.invoicePdf && <a href={invoice.invoicePdf} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 hover:text-ink-900" aria-label={`Download ${invoice.number}`}><Icon name="download" size={16}/></a>}</div></td></tr>)}</tbody></table></div>
        <div className="divide-y divide-slate-100 md:hidden">{invoices.map((invoice) => <div key={invoice.id} className="p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-ink-900">{invoice.number}</p><p className="mt-1 text-xs text-slate-500">{formatDate(invoice.date)} · {toTitle(invoice.plan)}</p></div><StatusBadge status={invoice.status}/></div><div className="mt-4 flex items-center justify-between"><p className="text-base font-bold text-ink-900">{formatCurrency(invoice.amount, invoice.currency)}</p><div className="flex gap-2">{invoice.hostedInvoiceUrl && <a href={invoice.hostedInvoiceUrl} className="btn-secondary min-h-9 px-3"><Icon name="external" size={15}/>View</a>}{invoice.invoicePdf && <a href={invoice.invoicePdf} className="btn-secondary min-h-9 px-3"><Icon name="download" size={15}/></a>}</div></div></div>)}</div>
      </>}
    </section>
    <ConfirmDialog open={dialogOpen} title="Cancel your subscription?" description={`Your ${subscription ? toTitle(subscription.plan) : ''} plan will remain active until ${formatDate(subscription?.currentPeriodEnd || null)}. You can resume at any time before then.`} confirmLabel="Cancel subscription" destructive loading={actionLoading} onCancel={() => setDialogOpen(false)} onConfirm={cancel}/>
  </>;
}

function Info({ label, value, icon }: {label: string; value: string; icon: 'calendar'|'clock'|'bookings'|'card'}) { return <div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><Icon name={icon} size={17}/></span><div><p className="text-xs text-slate-400">{label}</p><p className="mt-0.5 text-sm font-semibold text-ink-900">{value}</p></div></div>; }
function InvoiceSkeleton() { return <div className="space-y-0 divide-y divide-slate-100 px-5">{[1,2,3,4].map(i => <div key={i} className="grid grid-cols-4 gap-6 py-4"><div className="skeleton h-4 rounded"/><div className="skeleton h-4 rounded"/><div className="skeleton h-4 rounded"/><div className="skeleton h-4 rounded"/></div>)}</div>; }
