import { useState } from 'react';
import { Icon } from '../components/Icons';
import { PageHeader, Spinner, StatusBadge } from '../components/UI';
import { useToast } from '../lib/ToastContext';

const initialBookings = [
  { id: 'BK-1284', name: 'Sophia Bennett', service: 'Strategy consultation', date: 'Oct 4, 2026', time: '10:30 AM', status: 'confirmed', amount: '$180' },
  { id: 'BK-1283', name: 'Liam Carter', service: 'Product onboarding', date: 'Oct 4, 2026', time: '1:00 PM', status: 'confirmed', amount: '$240' },
  { id: 'BK-1282', name: 'Maya Rodriguez', service: 'Team workshop', date: 'Oct 4, 2026', time: '3:30 PM', status: 'pending', amount: '$450' },
  { id: 'BK-1281', name: 'Noah Williams', service: 'Follow-up session', date: 'Oct 5, 2026', time: '9:00 AM', status: 'confirmed', amount: '$120' },
  { id: 'BK-1280', name: 'Ava Thompson', service: 'Strategy consultation', date: 'Oct 5, 2026', time: '11:30 AM', status: 'cancelled', amount: '$180' },
];

export default function Bookings() {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const { toast } = useToast();
  const rows = initialBookings.filter((b) => (status === 'all' || b.status === status) && `${b.name} ${b.service} ${b.id}`.toLowerCase().includes(query.toLowerCase()));
  const save = (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setTimeout(() => { setSaving(false); setOpen(false); toast('Booking created successfully'); }, 700); };
  return <><PageHeader title="Bookings" description="Create, organize, and track every customer appointment." actions={<button className="btn-primary" onClick={() => setOpen(true)}><Icon name="plus" size={17}/>New booking</button>}/>
    <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Icon name="search" size={16} className="absolute left-3 top-3 text-slate-400"/><input className="field pl-9" placeholder="Search bookings…" value={query} onChange={(e) => setQuery(e.target.value)}/></div><select className="field sm:w-40" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="confirmed">Confirmed</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50/70 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Booking</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Service</th><th className="px-4 py-3">Date & time</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(b => <tr key={b.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-ink-900">{b.id}</td><td className="px-4 py-4 text-slate-700">{b.name}</td><td className="px-4 py-4 text-slate-600">{b.service}</td><td className="px-4 py-4"><p className="text-slate-700">{b.date}</p><p className="text-xs text-slate-400">{b.time}</p></td><td className="px-4 py-4 font-medium">{b.amount}</td><td className="px-4 py-4"><StatusBadge status={b.status}/></td><td className="px-5 py-4"><button className="text-slate-400"><Icon name="more"/></button></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-slate-100 md:hidden">{rows.map(b => <div key={b.id} className="p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-ink-900">{b.name}</p><p className="mt-0.5 text-xs text-slate-500">{b.id} · {b.service}</p></div><StatusBadge status={b.status}/></div><div className="mt-3 flex justify-between text-sm"><span className="text-slate-500">{b.date}, {b.time}</span><span className="font-semibold">{b.amount}</span></div></div>)}</div>
      {rows.length === 0 && <div className="p-12 text-center"><p className="font-semibold text-ink-900">No bookings found</p><p className="mt-1 text-sm text-slate-500">Try changing your filters.</p></div>}
    </section>
    {open && <div className="fixed inset-0 z-[70] flex items-end justify-center bg-ink-950/50 sm:items-center sm:p-4" onMouseDown={(e) => e.target === e.currentTarget && setOpen(false)}><form onSubmit={save} className="w-full max-w-lg rounded-t-2xl bg-white p-6 shadow-2xl sm:rounded-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-ink-900">Create booking</h2><p className="mt-1 text-sm text-slate-500">Add a new appointment to your calendar.</p></div><button type="button" onClick={() => setOpen(false)} className="p-2 text-slate-400"><Icon name="close"/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Customer name</span><input required className="field" placeholder="e.g. Olivia Parker"/></label><label className="sm:col-span-2"><span className="label">Service</span><select className="field"><option>Strategy consultation</option><option>Product onboarding</option><option>Team workshop</option></select></label><label><span className="label">Date</span><input required type="date" className="field" defaultValue="2026-10-06"/></label><label><span className="label">Time</span><input required type="time" className="field" defaultValue="10:00"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" disabled={saving}>{saving && <Spinner/>}Create booking</button></div></form></div>}
  </>;
}
